# Generated by Django 2.0 on 2018-01-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_announcement_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='cotent',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.Courses', verbose_name='Curso'),
        ),
    ]
